### ISSUE TITLE
Dialogoption anzeigen und auswählen

### ISSUE THREAD

**Issue by JanaDeppe** [project-cybersyn-game/project-cybersyn-game#16]
- [x] Dialogbaum als JSON-Format definieren und anlegen
- [x] Nächste Dialogoptionen anzeigen
- [x] Option (mit Klick oder mit Zahlen-Tasten?) auswählen
- [x] Nächste NPC-Antwort anzeigen

https://www.thebotanistgame.com/blog/2015/02/28/dialogue-in-phaserjs.html

**Comment by Hutmensch** [comment]
- [ ] Conditions
- [ ] Effects
- [ ] Character movement and interactions lock
- [ ] show speaking character name
- [ ] use full textbox
